# - name: Set up Python
#     # Corrected action syntax from ':' to '/'
#   uses: actions/setup-python@v4
#   with:
#     python-version: "3.10"

# - name: Install dependencies
#   run: |
#     python -m pip install --upgrade pip
#     pip install -r requirements.txt

# - name: Run linter (flake8)
#     # Using a single line command is often cleaner for simple commands
#   run: flake8 . || true

# - name: Run tests (pytest)
#     # The path fix in test_app.py makes the use of PYTHONPATH unnecessary here
#   run: pytest -v


name: CI/CD Pipeline for Shark Tank API

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # --- NEW STEPS START HERE ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
